export const previewResources = {
  de: {
    prototype: 'Skin-Vorschau', demo: 'Interaktive Demo · Beispieldaten', overview: 'Web UI', designer: 'Workflow Designer',
    light: 'Minimal Hell', dark: 'Minimal Dunkel', variant: 'Farbvariante', language: 'Sprache',
    status: 'Beispielzustand', idle: 'Bereit', running: 'Läuft', success: 'Erfolgreich', failed: 'Fehlgeschlagen',
    workspace: 'Arbeitsbereich', workflows: 'Workflows', administration: 'Verwaltung', settings: 'Einstellungen',
    machines: 'Maschinen', account: 'Demo-Arbeitsbereich', local: 'Lokal · keine Verbindung',
    subtitle: 'Automatisierungen im Blick. Alles an einem Ort.', newWorkflow: 'Neuer Workflow',
    total: 'Workflows', enabled: 'Aktiviert', successRate: 'Erfolgsquote', attention: 'Benötigt Aufmerksamkeit',
    totalHint: 'im Demo-Arbeitsbereich', enabledHint: 'bereit zur Ausführung', rateHint: 'in den letzten 24 Stunden', attentionHint: 'eine Ausführung fehlgeschlagen',
    allWorkflows: 'Alle Workflows', count: '{{count}} Workflows', search: 'Workflows durchsuchen', filter: 'Status filtern', allStates: 'Alle Zustände',
    name: 'Name', trigger: 'Auslöser', lastExecution: 'Letzte Ausführung', result: 'Status', manual: 'Manuell', scheduled: 'Zeitplan', event: 'Ereignis',
    service: 'Windows-Dienst prüfen', inventory: 'Systeminventar erfassen', backup: 'Datenbank sichern', cleanup: 'Temporäre Dateien bereinigen', certificate: 'Zertifikate überprüfen',
    folderService: 'Betrieb / Windows', folderInventory: 'Infrastruktur', folderBackup: 'Datenbanken', folderCleanup: 'Wartung', folderCertificate: 'Sicherheit',
    ago2: 'vor 2 Minuten', ago8: 'vor 8 Minuten', ago15: 'vor 15 Minuten', ago42: 'vor 42 Minuten', ago60: 'vor 1 Stunde', never: 'Noch nicht ausgeführt',
    empty: 'Keine passenden Workflows.', clearSearch: 'Filter zurücksetzen', selected: 'Workflow-Einstellungen', details: 'Details',
    machine: 'Zielmaschine', description: 'Beschreibung', descriptionValue: 'Prüft den Status des Windows-Dienstes und gibt das Ergebnis zurück.',
    activeLabel: 'Workflow aktiviert', activeHint: 'Kann in dieser Demo ausgewählt werden.', save: 'Änderungen übernehmen',
    saved: 'Änderungen in der Vorschau übernommen.', openDesigner: 'Im Designer ansehen',
    recent: 'Letzte Aktivitäten', completedEvent: 'Systeminventar erfasst', runningEvent: 'Dienstprüfung gestartet', failedEvent: 'Datenbanksicherung fehlgeschlagen',
    completedDetail: '24 Maschinen · alle erreichbar', runningDetail: 'WIN-SRV-01 · manueller Start', failedDetail: 'SQL-SRV-02 · Verbindung unterbrochen',
    controls: 'Bedienelemente', controlsHint: 'Hover, Fokus und Zustände direkt ausprobieren.', primary: 'Primäraktion', secondary: 'Sekundäraktion', disabled: 'Deaktiviert',
    sampleAction: 'Beispielaktion ausgeführt.', showDialog: 'Dialog öffnen', dialogTitle: 'Workflow erstellen', dialogHint: 'Ein neuer Eintrag wird nur für diese Vorschau angelegt.',
    workflowName: 'Workflow-Name', namePlaceholder: 'z. B. Dienstüberwachung', cancel: 'Abbrechen', create: 'Erstellen', close: 'Schließen',
    created: 'Demo-Workflow erstellt.', newFolder: 'Demo / Entwürfe',
    previewTitle: 'Minimal', previewHint: 'Gleicher Aufbau. Ruhige Flächen. Klare Zustände.',
    navigatePreview: 'Vorschauansicht auswählen', reset: 'Demo zurücksetzen', resetNotice: 'Beispieldaten zurückgesetzt.',
    screenReader: 'Navigation', note: 'Alle Änderungen bleiben in dieser Vorschau.',
  },
  en: {
    prototype: 'Skin preview', demo: 'Interactive demo · sample data', overview: 'Web UI', designer: 'Workflow designer',
    light: 'Minimal Light', dark: 'Minimal Dark', variant: 'Color variant', language: 'Language',
    status: 'Sample state', idle: 'Ready', running: 'Running', success: 'Succeeded', failed: 'Failed',
    workspace: 'Workspace', workflows: 'Workflows', administration: 'Administration', settings: 'Settings',
    machines: 'Machines', account: 'Demo workspace', local: 'Local · disconnected',
    subtitle: 'Your automations at a glance. Everything in one place.', newWorkflow: 'New workflow',
    total: 'Workflows', enabled: 'Enabled', successRate: 'Success rate', attention: 'Needs attention',
    totalHint: 'in this demo workspace', enabledHint: 'ready to execute', rateHint: 'over the last 24 hours', attentionHint: 'one execution failed',
    allWorkflows: 'All workflows', count: '{{count}} workflows', search: 'Search workflows', filter: 'Filter status', allStates: 'All states',
    name: 'Name', trigger: 'Trigger', lastExecution: 'Last execution', result: 'Status', manual: 'Manual', scheduled: 'Schedule', event: 'Event',
    service: 'Check Windows service', inventory: 'Collect system inventory', backup: 'Back up database', cleanup: 'Clean temporary files', certificate: 'Check certificates',
    folderService: 'Operations / Windows', folderInventory: 'Infrastructure', folderBackup: 'Databases', folderCleanup: 'Maintenance', folderCertificate: 'Security',
    ago2: '2 minutes ago', ago8: '8 minutes ago', ago15: '15 minutes ago', ago42: '42 minutes ago', ago60: '1 hour ago', never: 'Not executed yet',
    empty: 'No matching workflows.', clearSearch: 'Reset filters', selected: 'Workflow settings', details: 'Details',
    machine: 'Target machine', description: 'Description', descriptionValue: 'Checks the Windows service status and returns the result.',
    activeLabel: 'Workflow enabled', activeHint: 'Can be selected in this demo.', save: 'Apply changes',
    saved: 'Changes applied in the preview.', openDesigner: 'View in designer',
    recent: 'Recent activity', completedEvent: 'System inventory collected', runningEvent: 'Service check started', failedEvent: 'Database backup failed',
    completedDetail: '24 machines · all reachable', runningDetail: 'WIN-SRV-01 · manual start', failedDetail: 'SQL-SRV-02 · connection interrupted',
    controls: 'Controls', controlsHint: 'Try hover, focus and different states.', primary: 'Primary action', secondary: 'Secondary action', disabled: 'Disabled',
    sampleAction: 'Sample action completed.', showDialog: 'Open dialog', dialogTitle: 'Create workflow', dialogHint: 'A new entry is created only for this preview.',
    workflowName: 'Workflow name', namePlaceholder: 'e.g. Service monitoring', cancel: 'Cancel', create: 'Create', close: 'Close',
    created: 'Demo workflow created.', newFolder: 'Demo / Drafts',
    previewTitle: 'Minimal', previewHint: 'Same layout. Quiet surfaces. Clear states.',
    navigatePreview: 'Choose preview view', reset: 'Reset demo', resetNotice: 'Sample data reset.',
    screenReader: 'Navigation', note: 'All changes stay in this preview.',
  },
};
