export const designerResources = {
  de: {
    title: 'Dienstüberwachung',
    subtitle: 'Betrieb / Windows-Dienste',
    nodesCount: '4 Aktivitäten · 3 Verbindungen',
    library: 'Aktivitäten',
    libraryHint: 'Aktivität auswählen',
    search: 'Aktivitäten suchen',
    noResults: 'Keine passende Aktivität.',
    properties: 'Eigenschaften',
    configured: 'Konfiguriert',
    name: 'Anzeigename',
    machine: 'Zielmaschine',
    service: 'Dienstname',
    timeout: 'Zeitlimit (Sekunden)',
    trigger: 'Auslöser',
    manual: 'Manuell',
    scheduled: 'Zeitplan',
    interval: 'Alle 15 Minuten',
    output: 'Ausgabe',
    outputValue: 'Der Dienst läuft. Keine Aktion erforderlich.',
    logMessage: 'Protokollnachricht',
    logValue: 'Die Dienstprüfung konnte nicht abgeschlossen werden.',
    severity: 'Schweregrad',
    warning: 'Warnung',
    error: 'Fehler',
    propertiesHint: 'Änderungen gelten für dieses Beispiel.',
    fitView: 'Workflow einpassen',
    zoomIn: 'Vergrößern',
    zoomOut: 'Verkleinern',
    reset: 'Positionen zurücksetzen',
    canvas: 'Workflow-Zeichenfläche',
    canvasHint: 'Ziehen zum Verschieben · Scrollen zum Zoomen',
    canvasKeyboard: 'Aktivitäten mit Tab fokussieren; mit Eingabe auswählen; mit Pfeiltasten verschieben.',
    nodeMoved: 'Aktivität verschoben: {{x}}, {{y}}.',
    handle: 'Verbindungsport',
    edgeDescription: 'Verbindung zwischen zwei Aktivitäten.',
    controls: 'Canvas-Steuerung',
    interactive: 'Interaktion umschalten',
    minimap: 'Workflow-Übersicht',
    successPath: 'Erfolgreich',
    failedPath: 'Bei Fehler',
    selectedActivity: 'Ausgewählte Aktivität',
    execution: 'Ausführung',
    executionHint: 'Beispielausführung',
    activityColumn: 'Aktivität',
    statusColumn: 'Status',
    durationColumn: 'Dauer',
    idleSummary: 'Bereit für die Dienstprüfung auf {{machine}}.',
    runningSummary: 'Der Dienst „{{service}}“ auf {{machine}} wird geprüft.',
    successSummary: 'Dienstprüfung abgeschlossen. Der Dienst läuft.',
    failedSummary: 'Dienstprüfung fehlgeschlagen. Der Fehler wurde protokolliert.',
    nodes: { start: 'Start', check: 'Dienst prüfen', result: 'Ergebnis', error: 'Fehler protokollieren' },
    kinds: { start: 'Manueller Trigger', check: 'Windows-Dienst', result: 'Datenausgabe', error: 'Protokollierung' },
    descriptions: {
      start: 'Startet den Workflow manuell oder zu einem festen Zeitpunkt.',
      check: 'Prüft den Zustand eines Windows-Dienstes auf der Zielmaschine.',
      result: 'Stellt das Ergebnis der erfolgreichen Prüfung bereit.',
      error: 'Erfasst einen Fehler der Dienstprüfung im Ausführungsprotokoll.',
    },
    statuses: { idle: 'Bereit', running: 'Läuft', success: 'Erfolgreich', failed: 'Fehlgeschlagen', skipped: 'Nicht ausgeführt' },
  },
  en: {
    title: 'Service monitoring',
    subtitle: 'Operations / Windows services',
    nodesCount: '4 activities · 3 connections',
    library: 'Activities',
    libraryHint: 'Select an activity',
    search: 'Search activities',
    noResults: 'No matching activity.',
    properties: 'Properties',
    configured: 'Configured',
    name: 'Display name',
    machine: 'Target machine',
    service: 'Service name',
    timeout: 'Timeout (seconds)',
    trigger: 'Trigger',
    manual: 'Manual',
    scheduled: 'Schedule',
    interval: 'Every 15 minutes',
    output: 'Output',
    outputValue: 'The service is running. No action required.',
    logMessage: 'Log message',
    logValue: 'The service check could not be completed.',
    severity: 'Severity',
    warning: 'Warning',
    error: 'Error',
    propertiesHint: 'Changes apply to this example.',
    fitView: 'Fit workflow',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    reset: 'Reset positions',
    canvas: 'Workflow canvas',
    canvasHint: 'Drag to pan · Scroll to zoom',
    canvasKeyboard: 'Focus activities with Tab; select with Enter; move with arrow keys.',
    nodeMoved: 'Activity moved: {{x}}, {{y}}.',
    handle: 'Connection port',
    edgeDescription: 'Connection between two activities.',
    controls: 'Canvas controls',
    interactive: 'Toggle interaction',
    minimap: 'Workflow overview',
    successPath: 'Succeeded',
    failedPath: 'On failure',
    selectedActivity: 'Selected activity',
    execution: 'Execution',
    executionHint: 'Example execution',
    activityColumn: 'Activity',
    statusColumn: 'Status',
    durationColumn: 'Duration',
    idleSummary: 'Ready to check the service on {{machine}}.',
    runningSummary: 'Checking the “{{service}}” service on {{machine}}.',
    successSummary: 'Service check complete. The service is running.',
    failedSummary: 'Service check failed. The error was logged.',
    nodes: { start: 'Start', check: 'Check service', result: 'Result', error: 'Log error' },
    kinds: { start: 'Manual trigger', check: 'Windows service', result: 'Data output', error: 'Logging' },
    descriptions: {
      start: 'Starts the workflow manually or at a scheduled time.',
      check: 'Checks the state of a Windows service on the target machine.',
      result: 'Provides the result of the successful service check.',
      error: 'Records a service check error in the execution log.',
    },
    statuses: { idle: 'Ready', running: 'Running', success: 'Succeeded', failed: 'Failed', skipped: 'Not executed' },
  },
}
