using System.Text.Json;
using FluentAssertions;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging.Abstractions;
using Moq;
using NodePilot.Core.Interfaces;
using NodePilot.Core.Models;
using NodePilot.Engine.Activities;
using NodePilot.Engine.PowerShell;
using NodePilot.Engine.Tests.Helpers;
using Xunit;

namespace NodePilot.Engine.Tests.Activities;

public sealed class ScheduledTaskActivityTests : IDisposable
{
    private readonly Data.NodePilotDbContext _db;
    private readonly Mock<ICredentialStore> _credentialStore;
    private readonly Mock<IRemoteSessionFactory> _sessionFactory;
    private readonly Mock<IRemoteSession> _mockSession;
    private readonly PowerShellEngineFactory _engineFactory = new(NullLoggerFactory.Instance);
    private readonly Guid _machineId = Guid.NewGuid();
    private readonly Guid _credentialId = Guid.NewGuid();
    private string? _capturedScript;
    private string _scriptOutput = "OK";

    public ScheduledTaskActivityTests()
    {
        _db = TestDbContext.Create();
        _credentialStore = new Mock<ICredentialStore>();

        _mockSession = new Mock<IRemoteSession>();
        _mockSession
            .Setup(s => s.ExecuteScriptAsync(It.IsAny<string>(), It.IsAny<int?>(), It.IsAny<CancellationToken>()))
            .Callback<string, int?, CancellationToken>((script, _, _) => _capturedScript = script)
            .ReturnsAsync(() => new RemoteExecutionResult { Success = true, Output = _scriptOutput });
        _mockSession.Setup(s => s.DisposeAsync()).Returns(ValueTask.CompletedTask);

        _sessionFactory = new Mock<IRemoteSessionFactory>();
        _sessionFactory
            .Setup(f => f.CreateSessionAsync(It.IsAny<ManagedMachine>(), It.IsAny<Credential>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(_mockSession.Object);

        _db.Credentials.Add(new Credential { Id = _credentialId, Name = "C", Username = "u", EncryptedPassword = new byte[] { 1 } });
        _db.ManagedMachines.Add(new ManagedMachine
        {
            Id = _machineId, Name = "S", Hostname = "host.local",
            WinRmPort = 5985, DefaultCredentialId = _credentialId, IsReachable = true
        });
        _db.SaveChanges();

        _credentialStore
            .Setup(cs => cs.GetAsync(_credentialId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(new Credential { Id = _credentialId, Name = "C", Username = "u", EncryptedPassword = new byte[] { 1 } });
    }

    public void Dispose() => _db.Dispose();

    private ScheduledTaskActivity CreateActivity()
        => new(_sessionFactory.Object, _credentialStore.Object, _db, _engineFactory,
               new ConfigurationBuilder().Build());

    private StepExecutionContext Ctx()
        => new() { WorkflowExecutionId = Guid.NewGuid(), StepId = "step-1", TargetMachineId = _machineId, CredentialId = _credentialId };

    private static JsonElement Cfg(string json) => JsonDocument.Parse(json).RootElement;

    [Fact]
    public async Task UnknownAction_Throws()
    {
        var act = CreateActivity();
        Func<Task> call = () => act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"My\",\"action\":\"explode\"}"),
            CancellationToken.None);
        await call.Should().ThrowAsync<InvalidOperationException>().WithMessage("*explode*");
    }

    // The UI's action dropdown shows "Get / Status" as visual default but won't persist
    // 'get' to config until the user actually changes the dropdown. Workflows authored
    // without touching the dropdown (or generated by the AI) used to fail with
    // "unknown action ''". The activity now defaults to "get" so those workflows run.
    [Fact]
    public async Task MissingAction_DefaultsToGet()
    {
        _scriptOutput = "{\"TaskName\":\"AdobeGCInvoker-1.0\",\"State\":\"Ready\"}";
        var act = CreateActivity();
        var result = await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"AdobeGCInvoker-1.0\"}"),
            CancellationToken.None);
        result.Success.Should().BeTrue();
        _capturedScript.Should().Contain("Get-ScheduledTask -TaskName 'AdobeGCInvoker-1.0'");
        // PostProcess also defaults to "get" → output parameters get parsed.
        result.OutputParameters["taskName"].Should().Be("AdobeGCInvoker-1.0");
        result.OutputParameters["state"].Should().Be("Ready");
    }

    [Fact]
    public async Task EmptyAction_DefaultsToGet()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"X\",\"action\":\"\"}"),
            CancellationToken.None);
        _capturedScript.Should().Contain("Get-ScheduledTask -TaskName 'X'");
    }

    [Fact]
    public async Task MissingTaskName_Throws()
    {
        var act = CreateActivity();
        Func<Task> call = () => act.ExecuteAsync(Ctx(),
            Cfg("{\"action\":\"start\"}"),
            CancellationToken.None);
        await call.Should().ThrowAsync<InvalidOperationException>().WithMessage("*taskName*");
    }

    [Fact]
    public async Task NormalizeTaskPath_AddsLeadingAndTrailingBackslash()
    {
        ScheduledTaskActivity.NormalizeTaskPath("Microsoft\\Windows").Should().Be("\\Microsoft\\Windows\\");
        ScheduledTaskActivity.NormalizeTaskPath("\\Microsoft\\Windows").Should().Be("\\Microsoft\\Windows\\");
        ScheduledTaskActivity.NormalizeTaskPath("\\Microsoft\\Windows\\").Should().Be("\\Microsoft\\Windows\\");
        ScheduledTaskActivity.NormalizeTaskPath("").Should().Be("\\");
        ScheduledTaskActivity.NormalizeTaskPath(null!).Should().Be("\\");
    }

    [Fact]
    public async Task GetAction_ParsesJsonIntoOutputParameters()
    {
        _scriptOutput = "{\"TaskName\":\"My Task\",\"State\":2,\"LastRunTime\":\"2026-04-25T10:00:00\",\"LastTaskResult\":0,\"NextRunTime\":\"2026-04-26T10:00:00\"}";
        var act = CreateActivity();
        var result = await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"My Task\",\"action\":\"get\"}"),
            CancellationToken.None);
        result.Success.Should().BeTrue();
        result.OutputParameters["taskName"].Should().Be("My Task");
        result.OutputParameters["state"].Should().Be("2");
        result.OutputParameters["lastTaskResult"].Should().Be("0");
    }

    [Fact]
    public async Task GetAction_UsesCmdletFirstAndNarrowComFallbackForCorruptProvider()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"MicrosoftEdgeUpdateTaskMachineCore\",\"taskPath\":\"\\\\\",\"action\":\"get\"}"),
            CancellationToken.None);

        _capturedScript.Should().Contain("Get-ScheduledTask");
        _capturedScript.Should().Contain("-ErrorAction Stop");
        _capturedScript.Should().Contain("0x80041318");
        _capturedScript.Should().Contain("Schedule.Service");
        _capturedScript.Should().Contain("GetFolder('\\')");
        _capturedScript.Should().Contain("GetTask('MicrosoftEdgeUpdateTaskMachineCore')");
    }

    [Theory]
    [InlineData("start", "Start-ScheduledTask", ".Run($null)")]
    [InlineData("stop", "Stop-ScheduledTask", ".Stop(0)")]
    [InlineData("enable", "Enable-ScheduledTask", ".Enabled = $true")]
    [InlineData("disable", "Disable-ScheduledTask", ".Enabled = $false")]
    [InlineData("unregister", "Unregister-ScheduledTask", ".DeleteTask('Task', 0)")]
    public async Task ExistingTaskActions_UseCmdletFirstAndComFallback(
        string action, string cmdlet, string fallbackOperation)
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(),
            Cfg($"{{\"taskName\":\"Task\",\"taskPath\":\"\\\\Folder\\\\\",\"action\":\"{action}\"}}"),
            CancellationToken.None);

        _capturedScript.Should().Contain(cmdlet);
        _capturedScript.Should().Contain("-ErrorAction Stop");
        _capturedScript.Should().Contain("0x80041318");
        _capturedScript.Should().Contain("Schedule.Service");
        _capturedScript.Should().Contain("GetFolder('\\Folder')");
        _capturedScript.Should().Contain(fallbackOperation);
    }

    [Theory]
    [InlineData("\\", "\\")]
    [InlineData("Microsoft\\Windows", "\\Microsoft\\Windows")]
    [InlineData("\\Microsoft\\Windows\\", "\\Microsoft\\Windows")]
    public void NormalizeComFolderPath_UsesLeadingButNoTrailingSlash(string input, string expected)
    {
        ScheduledTaskActivity.NormalizeComFolderPath(input).Should().Be(expected);
    }

    [Fact]
    public async Task GetAction_HandlesArrayWrappedJson()
    {
        _scriptOutput = "[{\"TaskName\":\"X\",\"State\":\"Ready\"}]";
        var act = CreateActivity();
        var result = await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"X\",\"action\":\"get\"}"),
            CancellationToken.None);
        result.OutputParameters["state"].Should().Be("Ready");
    }

    [Fact]
    public async Task UnregisterAction_BuildsScriptWithConfirmFalse()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"Old\",\"action\":\"unregister\"}"),
            CancellationToken.None);
        _capturedScript.Should().Contain("Unregister-ScheduledTask");
        _capturedScript.Should().Contain("-Confirm:$false");
    }

    [Fact]
    public async Task RegisterDaily_BuildsActionTriggerPrincipalSettings()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(), Cfg(@"{
            ""action"":""register"",
            ""taskName"":""Nightly"",
            ""program"":""C:\\Tools\\backup.exe"",
            ""arguments"":""-quiet"",
            ""triggerType"":""daily"",
            ""startTime"":""02:00"",
            ""runAsUser"":""SYSTEM"",
            ""runLevel"":""highest"",
            ""description"":""Nightly backup"",
            ""force"":true
        }"), CancellationToken.None);
        _capturedScript.Should().Contain("$__npAction = New-ScheduledTaskAction -Execute 'C:\\Tools\\backup.exe'");
        _capturedScript.Should().Contain("-Argument '-quiet'");
        _capturedScript.Should().Contain("$__npTrigger = New-ScheduledTaskTrigger -Daily -At '02:00'");
        _capturedScript.Should().Contain("$__npPrincipal = New-ScheduledTaskPrincipal -UserId 'SYSTEM' -RunLevel Highest");
        _capturedScript.Should().Contain("Register-ScheduledTask");
        _capturedScript.Should().Contain("-Action $__npAction -Trigger $__npTrigger -Principal $__npPrincipal -Settings $__npSettings");
        _capturedScript.Should().Contain("-Description 'Nightly backup'");
        _capturedScript.Should().Contain("-Force");
        _capturedScript.Should().Contain("$ErrorActionPreference = 'Stop'");
        _capturedScript.Should().NotContain("Schedule.Service");
    }

    [Fact]
    public async Task RegisterWeekly_RequiresDaysOfWeek()
    {
        var act = CreateActivity();
        Func<Task> call = () => act.ExecuteAsync(Ctx(), Cfg(@"{
            ""action"":""register"",
            ""taskName"":""W"",
            ""program"":""C:\\x.exe"",
            ""triggerType"":""weekly"",
            ""startTime"":""03:00""
        }"), CancellationToken.None);
        await call.Should().ThrowAsync<InvalidOperationException>().WithMessage("*daysOfWeek*");
    }

    [Fact]
    public async Task RegisterWeekly_RejectsUnknownDay()
    {
        var act = CreateActivity();
        Func<Task> call = () => act.ExecuteAsync(Ctx(), Cfg(@"{
            ""action"":""register"",
            ""taskName"":""W"",
            ""program"":""C:\\x.exe"",
            ""triggerType"":""weekly"",
            ""startTime"":""03:00"",
            ""daysOfWeek"":[""Funday""]
        }"), CancellationToken.None);
        await call.Should().ThrowAsync<InvalidOperationException>().WithMessage("*Funday*");
    }

    [Fact]
    public async Task RegisterWeekly_BuildsCommaSeparatedDays()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(), Cfg(@"{
            ""action"":""register"",
            ""taskName"":""W"",
            ""program"":""C:\\x.exe"",
            ""triggerType"":""weekly"",
            ""startTime"":""03:00"",
            ""daysOfWeek"":[""Monday"",""Wednesday"",""Friday""],
            ""weeksInterval"":2
        }"), CancellationToken.None);
        _capturedScript.Should().Contain("-DaysOfWeek Monday,Wednesday,Friday");
        _capturedScript.Should().Contain("-WeeksInterval 2");
    }

    [Fact]
    public async Task RegisterAtLogon_NoStartTimeNeeded()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(), Cfg(@"{
            ""action"":""register"",
            ""taskName"":""L"",
            ""program"":""C:\\x.exe"",
            ""triggerType"":""atLogon""
        }"), CancellationToken.None);
        _capturedScript.Should().Contain("New-ScheduledTaskTrigger -AtLogOn");
    }

    [Fact]
    public async Task RegisterOnce_RequiresStartTime()
    {
        var act = CreateActivity();
        Func<Task> call = () => act.ExecuteAsync(Ctx(), Cfg(@"{
            ""action"":""register"",
            ""taskName"":""O"",
            ""program"":""C:\\x.exe"",
            ""triggerType"":""once""
        }"), CancellationToken.None);
        await call.Should().ThrowAsync<InvalidOperationException>().WithMessage("*startTime*");
    }

    [Fact]
    public async Task TaskNameWithApostrophe_IsEscaped()
    {
        var act = CreateActivity();
        await act.ExecuteAsync(Ctx(),
            Cfg("{\"taskName\":\"Tom's Job\",\"action\":\"start\"}"),
            CancellationToken.None);
        _capturedScript.Should().Contain("'Tom''s Job'");
    }
}
