using System.Data.Common;
using System.Text.RegularExpressions;
using Microsoft.Data.SqlClient;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Diagnostics;
using NodePilot.Data;
using Npgsql;

namespace NodePilot.TestCommons;

/// <summary>Creates and owns a disposable database on an explicitly configured test server.</summary>
public sealed class ProviderTestDatabase : IAsyncDisposable
{
    private readonly string _adminConnectionString;
    private readonly string _connectionString;
    private readonly string _databaseName;
    private bool _created;

    private ProviderTestDatabase(string provider, string configuredConnection)
    {
        Provider = provider;
        _databaseName = $"nodepilot_test_{Guid.NewGuid():N}";
        if (provider == "postgres")
        {
            var builder = new NpgsqlConnectionStringBuilder(configuredConnection)
            {
                Database = "postgres", Pooling = false, Timeout = 10, CommandTimeout = 30,
            };
            _adminConnectionString = builder.ConnectionString;
            builder.Database = _databaseName;
            _connectionString = builder.ConnectionString;
        }
        else
        {
            var builder = new SqlConnectionStringBuilder(configuredConnection)
            {
                InitialCatalog = "master", Pooling = false, ConnectTimeout = 10,
            };
            _adminConnectionString = builder.ConnectionString;
            builder.InitialCatalog = _databaseName;
            _connectionString = builder.ConnectionString;
        }
    }

    public string Provider { get; }

    public static bool IsConfigured(string provider)
        => !string.IsNullOrWhiteSpace(Environment.GetEnvironmentVariable(EnvironmentKey(provider)));

    public static async Task<ProviderTestDatabase> CreateAsync(
        string provider, bool readCommittedSnapshot = false, CancellationToken ct = default)
    {
        var configured = Environment.GetEnvironmentVariable(EnvironmentKey(provider));
        if (string.IsNullOrWhiteSpace(configured))
            throw new InvalidOperationException($"Set {EnvironmentKey(provider)} to an isolated test server.");

        var database = new ProviderTestDatabase(provider, configured);
        try
        {
            await database.ExecuteAdminAsync($"CREATE DATABASE {database.QuotedName()}", ct);
            database._created = true;
            if (provider == "sqlserver")
                await database.ExecuteAdminAsync(
                    $"ALTER DATABASE {database.QuotedName()} SET READ_COMMITTED_SNAPSHOT {(readCommittedSnapshot ? "ON" : "OFF")}", ct);
            await using var context = database.CreateContext();
            await context.Database.MigrateAsync(ct);
            return database;
        }
        catch
        {
            await database.DisposeAsync();
            throw;
        }
    }

    public NodePilotDbContext CreateContext(params IInterceptor[] interceptors)
    {
        var options = new DbContextOptionsBuilder<NodePilotDbContext>();
        if (Provider == "postgres") options.UseNpgsql(_connectionString, o => o.CommandTimeout(30));
        else options.UseSqlServer(_connectionString, o => o.CommandTimeout(30));
        options.ConfigureWarnings(w => w.Ignore(RelationalEventId.PendingModelChangesWarning));
        options.AddInterceptors(interceptors);
        return new NodePilotDbContext(options.Options);
    }

    public async ValueTask DisposeAsync()
    {
        if (!_created) return;
        // The identifier is generated by this instance, never taken from a connection string.
        var quoted = QuotedName();
        using var cleanup = new CancellationTokenSource(TimeSpan.FromSeconds(30));
        if (Provider == "postgres")
            await ExecuteAdminAsync($"DROP DATABASE IF EXISTS {quoted} WITH (FORCE)", cleanup.Token);
        else
        {
            await ExecuteAdminAsync($"ALTER DATABASE {quoted} SET SINGLE_USER WITH ROLLBACK IMMEDIATE", cleanup.Token);
            await ExecuteAdminAsync($"DROP DATABASE {quoted}", cleanup.Token);
        }
        _created = false;
    }

    private string QuotedName()
    {
        if (!Regex.IsMatch(_databaseName, "^nodepilot_test_[a-f0-9]{32}$", RegexOptions.CultureInvariant))
            throw new InvalidOperationException("Refusing to manage a database not owned by this test fixture.");
        return Provider == "postgres" ? $"\"{_databaseName}\"" : $"[{_databaseName}]";
    }

    private async Task ExecuteAdminAsync(string sql, CancellationToken ct)
    {
        await using DbConnection connection = Provider == "postgres"
            ? new NpgsqlConnection(_adminConnectionString)
            : new SqlConnection(_adminConnectionString);
        await connection.OpenAsync(ct);
        await using var command = connection.CreateCommand();
        command.CommandText = sql;
        command.CommandTimeout = 30;
        await command.ExecuteNonQueryAsync(ct);
    }

    private static string EnvironmentKey(string provider) => provider switch
    {
        "postgres" => "NODEPILOT_TEST_POSTGRES",
        "sqlserver" => "NODEPILOT_TEST_SQLSERVER",
        _ => throw new ArgumentOutOfRangeException(nameof(provider)),
    };
}
