using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Configuration;
using NodePilot.Core.Interfaces;
using NodePilot.Engine.PowerShell;

namespace NodePilot.Engine.Activities;

/// <summary>
/// Manages Windows Task Scheduler entries on a remote machine via the
/// <c>*-ScheduledTask</c> cmdlet family (Server 2012+).
///
/// Actions:
///   get          — Get-ScheduledTask, returns name/state/lastRunTime/lastTaskResult/nextRunTime
///                  as OutputParameters (parsed from JSON).
///   start        — Start-ScheduledTask.
///   stop         — Stop-ScheduledTask.
///   enable       — Enable-ScheduledTask.
///   disable      — Disable-ScheduledTask.
///   unregister   — Unregister-ScheduledTask (DESTRUCTIVE; warns in UI).
///   register     — Register-ScheduledTask. Creates a new task. Required: program, triggerType,
///                  startTime (for once/daily/weekly). Other fields documented per-trigger.
///
/// Common config:
///   taskName     string, required — leaf name (without path).
///   taskPath     string, default "\\" — folder path; "\\" = root.
///
/// Register-only config:
///   program             string, required — executable to run.
///   arguments           string, optional.
///   workingDirectory    string, optional.
///   triggerType         "once" | "daily" | "weekly" | "atLogon" | "atStartup".
///   startTime           string — required for once/daily/weekly. Format "yyyy-MM-ddTHH:mm:ss"
///                       (once) or "HH:mm" (daily/weekly). Validated upstream by PS.
///   daysOfWeek          string[] — required for weekly. Subset of {Monday..Sunday}.
///   weeksInterval       int, default 1 — only weekly.
///   daysInterval        int, default 1 — only daily.
///   runAsUser           string, default "SYSTEM".
///   runLevel            "limited" | "highest", default "limited".
///   description         string, optional.
///   force               bool, default false — overwrite existing task with same name.
///
/// Notes:
///   - Most actions require admin rights on the target. The activity does not enforce this;
///     the cmdlet will return the appropriate error.
///   - Register's principal/runAsUser path uses NT AUTHORITY built-ins ("SYSTEM",
///     "NETWORK SERVICE", "LOCAL SERVICE") implicitly. Domain users would also need a
///     password — out of scope for v1; document the limitation in the UI.
/// </summary>
public class ScheduledTaskActivity : BaseRemoteActivity
{
    private static readonly HashSet<string> KnownActions = new(StringComparer.OrdinalIgnoreCase)
    {
        "get", "start", "stop", "enable", "disable", "unregister", "register",
    };

    private static readonly HashSet<string> RegisterTriggerTypes = new(StringComparer.OrdinalIgnoreCase)
    {
        "once", "daily", "weekly", "atLogon", "atStartup",
    };

    private static readonly HashSet<string> ValidDaysOfWeek = new(StringComparer.OrdinalIgnoreCase)
    {
        "Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday",
    };

    public override string ActivityType => "scheduledTask";

    public ScheduledTaskActivity(
        IRemoteSessionFactory sessionFactory,
        ICredentialStore credentialStore,
        NodePilot.Data.NodePilotDbContext db,
        PowerShellEngineFactory engineFactory,
        IConfiguration config)
        : base(sessionFactory, credentialStore, db, engineFactory, config) { }

    protected override string BuildScript(JsonElement config, StepExecutionContext context)
    {
        // Default to "get" when action is missing or empty — the UI dropdown shows
        // "Get / Status" as visual default but won't persist 'get' to config unless the
        // user actively changes the dropdown. Workflows authored without touching the
        // dropdown (or generated by the AI) used to fail with "unknown action ''".
        // Empty-string ("action":"") and whitespace are also normalized so import paths
        // and legacy serialisers can't trip on it.
        var rawAction = config.GetStringOrNull("action");
        var action = (string.IsNullOrWhiteSpace(rawAction) ? "get" : rawAction).ToLowerInvariant();
        if (!KnownActions.Contains(action))
            throw new InvalidOperationException(
                $"Scheduled Task: unknown action '{action}'. Allowed: {string.Join(", ", KnownActions)}");

        var taskName = config.GetStringOrNull("taskName");
        if (string.IsNullOrWhiteSpace(taskName))
            throw new InvalidOperationException("Scheduled Task: 'taskName' is required");

        var taskPath = NormalizeTaskPath(config.GetString("taskPath", "\\"));

        var qName = PowerShellOperation.Literal(taskName);
        var qPath = PowerShellOperation.Literal(taskPath);
        var qComFolderPath = PowerShellOperation.Literal(NormalizeComFolderPath(taskPath));
        var qFullTaskPath = PowerShellOperation.Literal(taskPath + taskName);

        return action switch
        {
            // LastRunTime / LastTaskResult / NextRunTime are properties of ScheduledTaskInfo
            // (returned by Get-ScheduledTaskInfo), NOT Get-ScheduledTask. The old Select-Object
            // would silently coerce all three to $null because they don't exist on the task
            // object. Pipe through Get-ScheduledTaskInfo and merge fields into a single result.
            "get" => BuildExistingTaskScript(
                $"$__npTask = Get-ScheduledTask -TaskName {qName} -TaskPath {qPath} -ErrorAction Stop; " +
                "$__npInfo = $__npTask | Get-ScheduledTaskInfo -ErrorAction Stop; " +
                "[ordered]@{ " +
                "TaskName = $__npTask.TaskName; " +
                "State = $__npTask.State.ToString(); " +
                "LastRunTime = $__npInfo.LastRunTime; " +
                "LastTaskResult = $__npInfo.LastTaskResult; " +
                "NextRunTime = $__npInfo.NextRunTime " +
                "} | ConvertTo-Json -Compress",
                BuildComGetScript(), qName, qComFolderPath, qFullTaskPath),
            "start" => BuildExistingTaskScript(
                $"Start-ScheduledTask -TaskName {qName} -TaskPath {qPath} -ErrorAction Stop",
                "$__npRunning = $__npTask.Run($null)", qName, qComFolderPath, qFullTaskPath),
            "stop" => BuildExistingTaskScript(
                $"Stop-ScheduledTask -TaskName {qName} -TaskPath {qPath} -ErrorAction Stop",
                "[void]$__npTask.Stop(0)", qName, qComFolderPath, qFullTaskPath),
            "enable" => BuildExistingTaskScript(
                $"Enable-ScheduledTask -TaskName {qName} -TaskPath {qPath} -ErrorAction Stop",
                "$__npTask.Enabled = $true", qName, qComFolderPath, qFullTaskPath),
            "disable" => BuildExistingTaskScript(
                $"Disable-ScheduledTask -TaskName {qName} -TaskPath {qPath} -ErrorAction Stop",
                "$__npTask.Enabled = $false", qName, qComFolderPath, qFullTaskPath),
            "unregister" => BuildExistingTaskScript(
                $"Unregister-ScheduledTask -TaskName {qName} -TaskPath {qPath} -Confirm:$false -ErrorAction Stop",
                $"[void]$__npFolder.DeleteTask({qName}, 0)", qName, qComFolderPath, qFullTaskPath),
            "register" => "$ErrorActionPreference = 'Stop'; " + BuildRegisterScript(config, qName, qPath),
            _ => throw new InvalidOperationException($"Unknown scheduled-task action: {action}"),
        };
    }

    private static string BuildExistingTaskScript(
        string cmdletScript,
        string comOperation,
        string qName,
        string qComFolderPath,
        string qFullTaskPath)
    {
        // Get-ScheduledTask is backed by the MSFT_ScheduledTask CIM provider. A single orphaned
        // or semantically invalid task can make a server-side filtered query fail with 0x80041318,
        // even when the requested task is healthy. Keep the normal cmdlet path, but fall back to
        // the local Task Scheduler 2.0 automation API for this one provider-corruption HRESULT.
        // The fallback still runs *inside* the existing local/WinRM PowerShell session; it does
        // not introduce DCOM transport or new network credentials.
        return "try { " + cmdletScript + " } catch { " +
               "$__npProviderError = $_; " +
               "$__npProviderErrorText = \"$($__npProviderError.FullyQualifiedErrorId) $($__npProviderError.Exception.Message)\"; " +
               "if ($__npProviderErrorText -notmatch '0x80041318') { throw }; " +
               "$__npService = $null; $__npFolder = $null; $__npTask = $null; $__npRunning = $null; " +
               "try { " +
               "$__npServiceType = [Type]::GetTypeFromProgID('Schedule.Service'); " +
               "if ($null -eq $__npServiceType) { throw 'Task Scheduler automation API is unavailable' }; " +
               "$__npService = [Activator]::CreateInstance($__npServiceType); " +
               "$__npService.Connect(); " +
               $"$__npFolder = $__npService.GetFolder({qComFolderPath}); " +
               $"$__npTask = $__npFolder.GetTask({qName}); " +
               comOperation + "; " +
               "} catch { " +
               $"throw \"Scheduled Task {qFullTaskPath}: CIM provider failed with 0x80041318 and the local fallback also failed: $($_.Exception.Message)\" " +
               "} finally { " +
               "foreach ($__npComObject in @($__npRunning, $__npTask, $__npFolder, $__npService)) { " +
               "if ($null -ne $__npComObject -and [Runtime.InteropServices.Marshal]::IsComObject($__npComObject)) { " +
               "try { [void][Runtime.InteropServices.Marshal]::FinalReleaseComObject($__npComObject) } catch { } " +
               "} } " +
               "} " +
               "}";
    }

    private static string BuildComGetScript()
    {
        // TaskState enum: Unknown=0, Disabled=1, Queued=2, Ready=3, Running=4.
        // Convert dates explicitly so outputs stay invariant across target OS languages.
        return "$__npStateNames = @('Unknown', 'Disabled', 'Queued', 'Ready', 'Running'); " +
               "$__npStateCode = [int]$__npTask.State; " +
               "$__npState = if ($__npStateCode -ge 0 -and $__npStateCode -lt $__npStateNames.Count) " +
               "{ $__npStateNames[$__npStateCode] } else { \"Unknown($__npStateCode)\" }; " +
               "$__npLastRun = [datetime]$__npTask.LastRunTime; " +
               "$__npNextRun = [datetime]$__npTask.NextRunTime; " +
               "$__npLastRunText = if ($__npLastRun -eq [datetime]::MinValue) { '' } else { $__npLastRun.ToString('o', [Globalization.CultureInfo]::InvariantCulture) }; " +
               "$__npNextRunText = if ($__npNextRun -eq [datetime]::MinValue) { '' } else { $__npNextRun.ToString('o', [Globalization.CultureInfo]::InvariantCulture) }; " +
               "[ordered]@{ " +
               "TaskName = [string]$__npTask.Name; " +
               "State = $__npState; " +
               "LastRunTime = $__npLastRunText; " +
               "LastTaskResult = [int]$__npTask.LastTaskResult; " +
               "NextRunTime = $__npNextRunText " +
               "} | ConvertTo-Json -Compress";
    }

    private static string BuildRegisterScript(JsonElement config, string qName, string qPath)
    {
        var program = config.GetStringOrNull("program");
        if (string.IsNullOrWhiteSpace(program))
            throw new InvalidOperationException("Scheduled Task (register): 'program' is required");

        var triggerType = config.GetStringOrNull("triggerType")?.Trim();
        if (string.IsNullOrWhiteSpace(triggerType) || !RegisterTriggerTypes.Contains(triggerType))
            throw new InvalidOperationException(
                $"Scheduled Task (register): unknown triggerType '{triggerType}'. Allowed: {string.Join(", ", RegisterTriggerTypes)}");

        var qProgram = PowerShellOperation.Literal(program);
        var arguments = config.GetStringOrNull("arguments");
        var workingDir = config.GetStringOrNull("workingDirectory");
        var runAsUser = config.GetString("runAsUser", "SYSTEM");
        var runLevel = config.GetString("runLevel", "limited").ToLowerInvariant();
        var description = config.GetStringOrNull("description");
        var force = config.GetBool("force", false);

        if (runLevel != "limited" && runLevel != "highest")
            throw new InvalidOperationException("Scheduled Task (register): runLevel must be 'limited' or 'highest'");

        var sb = new StringBuilder();

        // __np prefix for internal variables: ProcessExecutionEngine captures every new $var the
        // script creates as an OutputParameter. The prefix keeps our scheduled-task scratch
        // variables out of that captured-variable channel, so the output stays clean.

        // Build the action object. -WorkingDirectory + -Argument are appended only if present
        // so we don't pass empty strings (the cmdlet handles missing args fine, but treats ''
        // and absent differently for some hosts).
        sb.Append("$__npAction = New-ScheduledTaskAction -Execute ").Append(qProgram);
        if (!string.IsNullOrWhiteSpace(arguments))
            sb.Append(" -Argument ").Append(PowerShellOperation.Literal(arguments));
        if (!string.IsNullOrWhiteSpace(workingDir))
            sb.Append(" -WorkingDirectory ").Append(PowerShellOperation.Literal(workingDir));
        sb.Append("; ");

        // Trigger object — switch by triggerType. startTime is validated to exist where required.
        sb.Append("$__npTrigger = ").Append(BuildTriggerExpression(config, triggerType!)).Append("; ");

        // Principal (user + run level). NT-AUTHORITY built-ins don't need a password and accept
        // -LogonType ServiceAccount; non-built-in names would fail without a password — we don't
        // attempt to detect that and let the cmdlet report it.
        var qUser = PowerShellOperation.Literal(runAsUser);
        var psRunLevel = runLevel == "highest" ? "Highest" : "Limited";
        sb.Append("$__npPrincipal = New-ScheduledTaskPrincipal -UserId ").Append(qUser)
          .Append(" -RunLevel ").Append(psRunLevel)
          .Append(" -LogonType ServiceAccount; ");

        sb.Append("$__npSettings = New-ScheduledTaskSettingsSet; ");

        sb.Append("Register-ScheduledTask -TaskName ").Append(qName)
          .Append(" -TaskPath ").Append(qPath)
          .Append(" -Action $__npAction -Trigger $__npTrigger -Principal $__npPrincipal -Settings $__npSettings");
        if (!string.IsNullOrWhiteSpace(description))
            sb.Append(" -Description ").Append(PowerShellOperation.Literal(description));
        if (force)
            sb.Append(" -Force");

        return sb.ToString();
    }

    private static string BuildTriggerExpression(JsonElement config, string triggerType)
    {
        var startTime = config.GetStringOrNull("startTime");

        // PS's New-ScheduledTaskTrigger accepts -At as a parsable datetime string. We pass it
        // through PowerShellQuoter so quotes/dollar-signs in user input can't break out.
        switch (triggerType.ToLowerInvariant())
        {
            case "atlogon":
                return "New-ScheduledTaskTrigger -AtLogOn";
            case "atstartup":
                return "New-ScheduledTaskTrigger -AtStartup";
            case "once":
                if (string.IsNullOrWhiteSpace(startTime))
                    throw new InvalidOperationException("Scheduled Task (register, once): 'startTime' is required");
                return $"New-ScheduledTaskTrigger -Once -At {PowerShellOperation.Literal(startTime)}";
            case "daily":
            {
                if (string.IsNullOrWhiteSpace(startTime))
                    throw new InvalidOperationException("Scheduled Task (register, daily): 'startTime' is required");
                var daysInterval = config.TryGetProperty("daysInterval", out var di) && di.TryGetInt32(out var div)
                    ? Math.Max(1, div) : 1;
                return $"New-ScheduledTaskTrigger -Daily -At {PowerShellOperation.Literal(startTime)} -DaysInterval {daysInterval}";
            }
            case "weekly":
            {
                if (string.IsNullOrWhiteSpace(startTime))
                    throw new InvalidOperationException("Scheduled Task (register, weekly): 'startTime' is required");
                var days = config.TryGetProperty("daysOfWeek", out var dEl) && dEl.ValueKind == JsonValueKind.Array
                    ? dEl.EnumerateArray()
                          .Select(d => d.GetString())
                          .Where(s => !string.IsNullOrWhiteSpace(s))
                          .ToList()
                    : new List<string?>();
                if (days.Count == 0)
                    throw new InvalidOperationException("Scheduled Task (register, weekly): 'daysOfWeek' must list at least one day");
                foreach (var d in days)
                {
                    if (!ValidDaysOfWeek.Contains(d!))
                        throw new InvalidOperationException(
                            $"Scheduled Task (register, weekly): unknown day '{d}'. Allowed: Monday..Sunday");
                }
                var weeksInterval = config.TryGetProperty("weeksInterval", out var wi) && wi.TryGetInt32(out var wiv)
                    ? Math.Max(1, wiv) : 1;
                // PS expects a comma-separated list of unquoted enum tokens for -DaysOfWeek.
                // Whitelist above ensures we only inject vetted day names.
                var joined = string.Join(",", days.Select(d => d!.Trim()));
                return $"New-ScheduledTaskTrigger -Weekly -At {PowerShellOperation.Literal(startTime)} " +
                       $"-DaysOfWeek {joined} -WeeksInterval {weeksInterval}";
            }
            default:
                throw new InvalidOperationException($"Unknown triggerType: {triggerType}");
        }
    }

    /// <summary>
    /// Normalizes the task-path so PowerShell's <c>-TaskPath</c> never sees a missing slash.
    /// Accepts both "Microsoft\\Windows" and "\\Microsoft\\Windows\\" — output always starts
    /// and ends with a backslash.
    /// </summary>
    internal static string NormalizeTaskPath(string raw)
    {
        if (string.IsNullOrWhiteSpace(raw)) return "\\";
        var p = raw.Trim();
        if (!p.StartsWith('\\')) p = "\\" + p;
        if (!p.EndsWith('\\')) p += "\\";
        return p;
    }

    /// <summary>
    /// Task Scheduler's automation API accepts the root as <c>\</c>, but rejects trailing
    /// separators on non-root folder paths. Keep the public/cmdlet path convention unchanged
    /// and derive the automation-folder form only for the narrow CIM-corruption fallback.
    /// </summary>
    internal static string NormalizeComFolderPath(string raw)
    {
        var normalized = NormalizeTaskPath(raw);
        return normalized == "\\" ? normalized : normalized.TrimEnd('\\');
    }

    protected override ActivityResult PostProcess(ActivityResult raw, JsonElement config)
    {
        var rawAction = config.GetStringOrNull("action");
        var action = (string.IsNullOrWhiteSpace(rawAction) ? "get" : rawAction).ToLowerInvariant();
        if (action != "get" || !raw.Success || string.IsNullOrWhiteSpace(raw.Output))
            return raw;

        var op = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (PowerShellOperation.TryParseJson(raw.Output!, out var parsedDoc, out _))
        {
            using var doc = parsedDoc!;
            var root = doc.RootElement;
            // ConvertTo-Json wraps single-result objects in {} but multi-result in []. Get-ScheduledTask
            // for a single name is single-result, but we still defensively unwrap a 1-array.
            if (root.ValueKind == JsonValueKind.Array && root.GetArrayLength() == 1)
                root = root[0];

            if (root.ValueKind == JsonValueKind.Object)
            {
                PowerShellOperation.CopyStringField(root, "TaskName", op, "taskName");
                PowerShellOperation.CopyStringField(root, "State", op, "state");
                PowerShellOperation.CopyStringField(root, "LastRunTime", op, "lastRunTime");
                PowerShellOperation.CopyStringField(root, "LastTaskResult", op, "lastTaskResult");
                PowerShellOperation.CopyStringField(root, "NextRunTime", op, "nextRunTime");
            }
        }
        else
        {
            // Output wasn't JSON (e.g. because the task was missing and PowerShell printed an
            // error instead) — we leave Success/Output unchanged and return empty
            // OutputParameters; the caller sees ErrorOutput anyway.
        }

        if (op.Count == 0) return raw;

        return new ActivityResult
        {
            Success = raw.Success,
            Output = raw.Output,
            ErrorOutput = raw.ErrorOutput,
            Duration = raw.Duration,
            OutputParameters = op,
        };
    }

}
