using System.Globalization;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Microsoft.AspNetCore.Http;
using NodePilot.Core.WorkflowDefinitions;

namespace NodePilot.Api.Security;

/// <summary>
/// Security contract shared by webhook publish/import validation and request-time HMAC
/// verification. NodePilot HMAC v2 deliveries use this canonical signing input:
/// <c>"NodePilot-HMAC-v2\n" + unixTimestamp + "\n" + deliveryId + "\n"
/// + upperMethod + "\n" + escapedPath + "\n" + canonicalQuery + "\n" + rawBodyBytes</c>.
/// </summary>
internal static class WebhookHmacSecurity
{
    internal const string SignatureModeV2 = "nodepilot-hmac-v2";
    internal const string LegacySignatureMode = "hmac";
    internal const int MinSecretBytes = 32;
    internal const int MinDeliveryIdLength = 16;
    internal const int MaxDeliveryIdLength = 128;
    internal const string DefaultSignatureHeader = "X-NodePilot-Signature";
    internal const string TimestampHeader = "X-NodePilot-Timestamp";
    internal const string DeliveryIdHeader = "X-NodePilot-Delivery-Id";
    internal static readonly TimeSpan AllowedClockSkew = TimeSpan.FromMinutes(5);

    internal static string? ValidateDefinition(string definitionJson)
    {
        if (!WorkflowDefinitionDocument.TryParse(definitionJson, out var definition)
            || definition is null)
        {
            return null; // Structural validation owns malformed definitions.
        }

        // Validate disabled nodes too. Import/publish are the security boundary for stored
        // definitions, and a disabled trigger can be enabled later without changing its config.
        foreach (var trigger in definition.Nodes.Where(x =>
                     string.Equals(x.Type, "webhookTrigger", StringComparison.Ordinal)))
        {
            var config = trigger.Data.Config;
            if (config.ValueKind != JsonValueKind.Object
                || !config.TryGetProperty("signatureMode", out var mode))
            {
                continue;
            }

            if (mode.ValueKind is JsonValueKind.Null or JsonValueKind.Undefined)
                continue;
            if (mode.ValueKind != JsonValueKind.String)
                return $"webhookTrigger '{trigger.Id}' has an invalid signatureMode";

            var modeValue = mode.GetString();
            if (string.IsNullOrWhiteSpace(modeValue)
                || string.Equals(modeValue, "header", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }
            if (string.Equals(modeValue, LegacySignatureMode, StringComparison.OrdinalIgnoreCase))
            {
                return $"webhookTrigger '{trigger.Id}' uses legacy signatureMode '{LegacySignatureMode}', which is no longer accepted; change it to '{SignatureModeV2}' and update the sender to the version-2 wire format";
            }
            if (!IsV2Mode(modeValue))
                return $"webhookTrigger '{trigger.Id}' uses unsupported signatureMode '{modeValue}'";

            var secret = config.TryGetProperty("secret", out var configuredSecret)
                ? configuredSecret.GetString()
                : null;
            if (!TryGetKeyBytes(secret, out var key))
            {
                return $"webhookTrigger '{trigger.Id}' uses HMAC and requires a secret with at least {MinSecretBytes} UTF-8 bytes generated by a cryptographically secure random-number generator";
            }

            CryptographicOperations.ZeroMemory(key);
        }

        return null;
    }

    internal static bool IsV2Mode(string? mode)
        => string.Equals(mode, SignatureModeV2, StringComparison.OrdinalIgnoreCase);

    internal static bool TryGetKeyBytes(string? secret, out byte[] key)
    {
        key = [];
        if (string.IsNullOrWhiteSpace(secret)) return false;

        key = Encoding.UTF8.GetBytes(secret);
        if (key.Length >= MinSecretBytes) return true;

        CryptographicOperations.ZeroMemory(key);
        key = [];
        return false;
    }

    internal static bool TryParseFreshnessHeaders(
        string? timestampHeader,
        string? deliveryIdHeader,
        DateTime nowUtc,
        out string timestamp,
        out string deliveryId)
    {
        // Do not trim signed fields. Accepting two textual representations for the same
        // logical timestamp/delivery makes external implementations disagree about the MAC
        // bytes and can hide control characters at either edge.
        timestamp = timestampHeader ?? string.Empty;
        deliveryId = deliveryIdHeader ?? string.Empty;

        if (!long.TryParse(timestamp, NumberStyles.None, CultureInfo.InvariantCulture, out var unixSeconds))
            return false;

        DateTime signedAtUtc;
        try
        {
            signedAtUtc = DateTimeOffset.FromUnixTimeSeconds(unixSeconds).UtcDateTime;
        }
        catch (ArgumentOutOfRangeException)
        {
            return false;
        }

        if ((signedAtUtc - nowUtc).Duration() > AllowedClockSkew)
            return false;

        if (deliveryId.Length is < MinDeliveryIdLength or > MaxDeliveryIdLength)
            return false;

        // Header values are canonicalized with newline delimiters. Reject controls (including
        // CR/LF) and non-ASCII characters so every sender can reproduce the same byte sequence.
        if (deliveryId.Any(c => c < 0x21 || c > 0x7e))
            return false;

        return true;
    }

    internal static byte[] ComputeMac(
        ReadOnlySpan<byte> key,
        string timestamp,
        string deliveryId,
        string method,
        string canonicalPath,
        string canonicalQuery,
        ReadOnlySpan<byte> rawBody)
    {
        using var hmac = IncrementalHash.CreateHMAC(HashAlgorithmName.SHA256, key);
        hmac.AppendData("NodePilot-HMAC-v2\n"u8);
        hmac.AppendData(Encoding.ASCII.GetBytes(timestamp));
        hmac.AppendData("\n"u8);
        hmac.AppendData(Encoding.ASCII.GetBytes(deliveryId));
        hmac.AppendData("\n"u8);
        hmac.AppendData(Encoding.ASCII.GetBytes(method.ToUpperInvariant()));
        hmac.AppendData("\n"u8);
        hmac.AppendData(Encoding.UTF8.GetBytes(canonicalPath));
        hmac.AppendData("\n"u8);
        hmac.AppendData(Encoding.UTF8.GetBytes(canonicalQuery));
        hmac.AppendData("\n"u8);
        hmac.AppendData(rawBody);
        return hmac.GetHashAndReset();
    }

    /// <summary>
    /// Returns the path representation covered by HMAC v2. <see cref="PathString.ToUriComponent"/>
    /// produces the escaped form seen on the wire while preserving slash separators. PathBase is
    /// included so deployments mounted below a reverse-proxy prefix cannot move a signed request
    /// to a different NodePilot endpoint without invalidating the MAC.
    /// </summary>
    internal static string CanonicalizePath(PathString pathBase, PathString path)
        => pathBase.Add(path).ToUriComponent();

    /// <summary>
    /// Canonical query representation: every decoded key/value pair is UTF-8 percent-encoded
    /// using only RFC 3986 unreserved characters, sorted ordinally by encoded key, and joined
    /// as <c>key=value&amp;key=value</c>. Duplicate values keep their request order because that
    /// order is also visible in the forwarded workflow parameter. An absent
    /// query is the empty string; <c>?flag</c> and <c>?flag=</c> intentionally canonicalize alike
    /// because ASP.NET exposes the same input value to workflows for both forms.
    /// </summary>
    internal static string CanonicalizeQuery(IQueryCollection query)
    {
        var groups = new List<(string Key, IReadOnlyList<string> Values)>();
        foreach (var (key, values) in query)
        {
            var encodedKey = PercentEncodeQueryComponent(key);
            if (values.Count == 0)
            {
                groups.Add((encodedKey, [string.Empty]));
                continue;
            }

            groups.Add((encodedKey, values
                .Select(static value => PercentEncodeQueryComponent(value ?? string.Empty))
                .ToList()));
        }

        groups.Sort(static (left, right) => StringComparer.Ordinal.Compare(left.Key, right.Key));
        return string.Join("&", groups.SelectMany(static group =>
            group.Values.Select(value => $"{group.Key}={value}")));
    }

    private static string PercentEncodeQueryComponent(string value)
    {
        var bytes = Encoding.UTF8.GetBytes(value);
        var result = new StringBuilder(bytes.Length);
        foreach (var b in bytes)
        {
            if ((b >= (byte)'A' && b <= (byte)'Z')
                || (b >= (byte)'a' && b <= (byte)'z')
                || (b >= (byte)'0' && b <= (byte)'9')
                || b is (byte)'-' or (byte)'.' or (byte)'_' or (byte)'~')
            {
                result.Append((char)b);
            }
            else
            {
                result.Append('%');
                result.Append(b.ToString("X2", CultureInfo.InvariantCulture));
            }
        }
        return result.ToString();
    }
}
