import { readFile } from 'node:fs/promises';
import { workflows } from './demo-data.mjs';

// Generated by the real ScorchImporter from the adjacent synthetic .ois_export.
// Only the API persistence response is simulated; nothing reaches a database.
const parsed = JSON.parse(await readFile(new URL('./fixtures/import-result.json', import.meta.url), 'utf8'));
export const importFile = new URL('./fixtures/Daily-Log-Archive.ois_export', import.meta.url);
const expectedBytes = await readFile(importFile);
export const importedId = '70707070-7070-7070-7070-707070707070';
export const importedName = parsed.workflows[0].name;
export function createImportDemo() {
  let imported = false;
  const runbook = parsed.workflows[0];
  const workflow = {
    ...workflows[0], id: importedId, name: runbook.name, description: runbook.description,
    definitionJson: runbook.definitionJson, version: 1, isEnabled: false,
    activityCount: runbook.activityCount, triggerTypes: ['manualTrigger'],
    checkedOutByUserId: null, checkedOutByUserName: null, checkedOutAt: null,
    lastExecution: null, successCount: 0, totalCount: 0, avgDurationMs: 0,
  };
  return {
    accept(request) {
      if (imported || !request.postDataBuffer()?.equals(expectedBytes))
        throw new Error('Only the fixed demo .ois_export may be imported once.');
      imported = true;
      return {
        created: 1,
        workflows: [{id: importedId, name: runbook.name, originalName: null,
          activityCount: runbook.activityCount, heuristicCount: runbook.heuristicCount,
          fallbackCount: runbook.fallbackCount, folderPath: '/'}],
        variables: [], warnings: parsed.warnings, errors: parsed.errors,
      };
    },
    response(url) {
      if (!imported) return undefined;
      if (url.pathname === '/api/workflows') return [...workflows, workflow];
      if (url.pathname === `/api/workflows/${importedId}`) return workflow;
      if ([`/api/workflows/${importedId}/step-health`, `/api/workflows/${importedId}/step-stats`].includes(url.pathname)) return {};
      if (url.pathname === '/api/executions' && url.searchParams.get('workflowId') === importedId) return [];
      return undefined;
    },
  };
}
