import { resolveSkin, type SkinId, type Theme, type ThemeBase } from '../stores/themeStore';

/**
 * Pre-rendered app icons generated by scripts/generate-logo-skins.py from appicon.original.png.
 * Minimal skins reuse the light/dark blue assets; ION reuses Nebula's cyan asset. Shared by `BrandLogo` and
 * `applyFavicon` so the brand mark and favicon follow the selected skin together.
 */
// Resolved against the build's base URL, not the origin root: a deployment served from a
// sub-path would otherwise request the icons from the wrong place and render no brand mark.
const asset = (file: string): string => `${import.meta.env.BASE_URL}${file}`;

export const APP_ICON_BY_SKIN: Record<SkinId, string> = {
  light: asset('appicon-light.png'),
  dark: asset('appicon-dark.png'),
  'dark-lila': asset('appicon-dark-lila.png'),
  'light-grey': asset('appicon-light-grey.png'),
  'dark-bank': asset('appicon-dark-bank.png'),
  'light-bank': asset('appicon-light-bank.png'),
  'dark-nebula': asset('appicon-dark-nebula.png'),
  'light-minimal': asset('appicon-light.png'),
  'dark-minimal': asset('appicon-dark.png'),
  'dark-ion': asset('appicon-dark-nebula.png'),
};

/**
 * Resolves the icon path for a theme preference, which may be `system`.
 * `system` follows the resolved light or dark base, the same as `BrandLogo`.
 */
export function appIconForTheme(theme: Theme, resolvedBase: ThemeBase): string {
  const skin: SkinId = theme === 'system' ? resolvedBase : resolveSkin(theme);
  return APP_ICON_BY_SKIN[skin] ?? APP_ICON_BY_SKIN.light;
}

/**
 * Writes the skin-matched icon into the `<link rel="icon">` element so the browser tab
 * recolors with the active skin. Skips the DOM write when the href already matches, which
 * avoids href churn on every store tick, and creates the link element if `index.html` has
 * none. Safe to call before first paint, like `applyTheme`.
 */
export function applyFavicon(theme: Theme, resolvedBase: ThemeBase): void {
  const href = appIconForTheme(theme, resolvedBase);
  let link = document.querySelector<HTMLLinkElement>('link[rel="icon"]');
  if (!link) {
    link = document.createElement('link');
    link.rel = 'icon';
    link.type = 'image/png';
    document.head.appendChild(link);
  }
  if (link.getAttribute('href') !== href) link.setAttribute('href', href);
}
