import { resolveSkin, type SkinId, type Theme, type ThemeBase } from '../stores/themeStore';

/**
 * One pre-rendered app icon per skin, generated by scripts/generate-logo-skins.py from
 * appicon.original.png. Each icon is hue-matched to that skin's `--color-primary` accent so
 * the brand mark and the favicon follow the selected skin. Shared by `BrandLogo` and
 * `applyFavicon` so both use the same image.
 */
export const APP_ICON_BY_SKIN: Record<SkinId, string> = {
  light: '/appicon-light.png',
  dark: '/appicon-dark.png',
  'dark-lila': '/appicon-dark-lila.png',
  'light-grey': '/appicon-light-grey.png',
  'dark-bank': '/appicon-dark-bank.png',
  'light-bank': '/appicon-light-bank.png',
  'dark-nebula': '/appicon-dark-nebula.png',
};

/**
 * Resolves the icon path for a theme preference, which may be `system`.
 * `system` follows the resolved light or dark base, the same as `BrandLogo`.
 */
export function appIconForTheme(theme: Theme, resolvedBase: ThemeBase): string {
  const skin: SkinId = theme === 'system' ? resolvedBase : resolveSkin(theme);
  return APP_ICON_BY_SKIN[skin] ?? APP_ICON_BY_SKIN.light;
}

/**
 * Writes the skin-matched icon into the `<link rel="icon">` element so the browser tab
 * recolors with the active skin. Skips the DOM write when the href already matches, which
 * avoids href churn on every store tick, and creates the link element if `index.html` has
 * none. Safe to call before first paint, like `applyTheme`.
 */
export function applyFavicon(theme: Theme, resolvedBase: ThemeBase): void {
  const href = appIconForTheme(theme, resolvedBase);
  let link = document.querySelector<HTMLLinkElement>('link[rel="icon"]');
  if (!link) {
    link = document.createElement('link');
    link.rel = 'icon';
    link.type = 'image/png';
    document.head.appendChild(link);
  }
  if (link.getAttribute('href') !== href) link.setAttribute('href', href);
}
