import { resolveSkin, type SkinId, type Theme, type ThemeBase } from '../stores/themeStore';

/**
 * One pre-rendered app icon per skin (generated by scripts/generate-logo-skins.py from
 * appicon.original.png). Each is hue-matched to that skin's `--color-primary` accent, so
 * the brand mark AND the browser favicon track the selected color skin instead of
 * clashing with it. Shared between `BrandLogo` (in-app logo) and `applyFavicon`
 * (browser tab / bookmark icon) so the two never drift apart.
 */
export const APP_ICON_BY_SKIN: Record<SkinId, string> = {
  light: '/appicon-light.png',
  dark: '/appicon-dark.png',
  'dark-lila': '/appicon-dark-lila.png',
  'light-grey': '/appicon-light-grey.png',
  'dark-sparkasse': '/appicon-dark-sparkasse.png',
  'light-sparkasse': '/appicon-light-sparkasse.png',
  'dark-nebula': '/appicon-dark-nebula.png',
};

/**
 * Resolve the concrete icon path for a (possibly `system`) theme preference.
 * `system` follows the resolved light/dark base — exactly what `BrandLogo` does.
 */
export function appIconForTheme(theme: Theme, resolvedBase: ThemeBase): string {
  const skin: SkinId = theme === 'system' ? resolvedBase : resolveSkin(theme);
  return APP_ICON_BY_SKIN[skin] ?? APP_ICON_BY_SKIN.light;
}

/**
 * Write the skin-matched icon into the `<link rel="icon">` element so the browser tab
 * recolors with the active skin. Idempotent: skips the DOM write when the href already
 * matches (avoids needless href churn on every store tick). Creates the link element if
 * `index.html` shipped without one. Safe to call pre-paint (used at App module scope,
 * mirroring `applyTheme`).
 */
export function applyFavicon(theme: Theme, resolvedBase: ThemeBase): void {
  const href = appIconForTheme(theme, resolvedBase);
  let link = document.querySelector<HTMLLinkElement>('link[rel="icon"]');
  if (!link) {
    link = document.createElement('link');
    link.rel = 'icon';
    link.type = 'image/png';
    document.head.appendChild(link);
  }
  if (link.getAttribute('href') !== href) link.setAttribute('href', href);
}
