// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodePilot.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NodePilot.Data.Migrations
{
    [DbContext(typeof(NodePilotDbContext))]
    [Migration("20260511183144_InitialBaseline")]
    partial class InitialBaseline
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NodePilot.Core.Models.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Action", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("ResourceId", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ClusterLeader", b =>
                {
                    b.Property<string>("Resource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRenewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LeaseEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerNodeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Resource");

                    b.ToTable("ClusterLeaders");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("NodePilot.Core.Models.GlobalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalVariables");
                });

            modelBuilder.Entity("NodePilot.Core.Models.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key", "WorkflowId")
                        .IsUnique();

                    b.ToTable("IdempotencyKeys");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ManagedMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultCredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsReachable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastConnectivityCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<int>("WinRmPort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCredentialId");

                    b.ToTable("ManagedMachines");
                });

            modelBuilder.Entity("NodePilot.Core.Models.RevokedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedFolderPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrincipalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("FolderId", "PrincipalType", "PrincipalKey")
                        .IsUnique();

                    b.ToTable("SharedFolderPermissions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedWorkflowFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("ParentFolderId", "Name")
                        .IsUnique();

                    b.ToTable("SharedWorkflowFolders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 0,
                            Name = "Root",
                            Path = "/"
                        });
                });

            modelBuilder.Entity("NodePilot.Core.Models.StepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorOutput")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("OutputParametersJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StepName")
                        .HasColumnType("text");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TargetMachine")
                        .HasColumnType("text");

                    b.Property<string>("TraceOutput")
                        .HasColumnType("text");

                    b.Property<string>("VariablesSnapshot")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionId", "StartedAt");

                    b.HasIndex("WorkflowExecutionId", "Status");

                    b.ToTable("StepExecutions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SystemHealthHeartbeat", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ServiceName");

                    b.ToTable("SystemHealth");
                });

            modelBuilder.Entity("NodePilot.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("KnownGroupSidsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NodePilot.Core.Models.UserWorkflowFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "ParentFolderId");

                    b.ToTable("UserWorkflowFolders");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedOutByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("TriggerTypesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckedOutByUserId");

                    b.HasIndex("FolderId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CallDepth")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputParametersJson")
                        .HasColumnType("text");

                    b.Property<string>("OwnerNodeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnData")
                        .HasColumnType("text");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StartedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("TraceId");

                    b.HasIndex("StartedAt", "Status");

                    b.HasIndex("Status", "StartedAt")
                        .IsDescending(false, true)
                        .HasAnnotation("SqlServer:Include", new[] { "WorkflowId", "CompletedAt", "TriggeredBy" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "StartedAt"), new[] { "WorkflowId", "CompletedAt", "TriggeredBy" });

                    b.HasIndex("WorkflowId", "StartedAt")
                        .IsDescending(false, true)
                        .HasAnnotation("SqlServer:Include", new[] { "Status", "CompletedAt" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("WorkflowId", "StartedAt"), new[] { "Status", "CompletedAt" });

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowFolderAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("UserId", "WorkflowId")
                        .IsUnique();

                    b.ToTable("WorkflowFolderAssignments");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowStats", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<double?>("AvgDurationMsWindow")
                        .HasColumnType("double precision");

                    b.Property<int>("CancelledWindow")
                        .HasColumnType("integer");

                    b.Property<int>("FailedWindow")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastExecutionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P50DurationMsWindow")
                        .HasColumnType("double precision");

                    b.Property<double?>("P95DurationMsWindow")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SucceededWindow")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExecutions")
                        .HasColumnType("integer");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer");

                    b.HasKey("WorkflowId");

                    b.ToTable("WorkflowStats");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowVersions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ManagedMachine", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Credential", "DefaultCredential")
                        .WithMany()
                        .HasForeignKey("DefaultCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultCredential");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedFolderPermission", b =>
                {
                    b.HasOne("NodePilot.Core.Models.SharedWorkflowFolder", "Folder")
                        .WithMany("Permissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedWorkflowFolder", b =>
                {
                    b.HasOne("NodePilot.Core.Models.SharedWorkflowFolder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NodePilot.Core.Models.StepExecution", b =>
                {
                    b.HasOne("NodePilot.Core.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Workflow", b =>
                {
                    b.HasOne("NodePilot.Core.Models.SharedWorkflowFolder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowExecution", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Workflow", "Workflow")
                        .WithMany("Executions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowStats", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowVersion", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedWorkflowFolder", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Workflow", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowExecution", b =>
                {
                    b.Navigation("Steps");
                });
            MigrationModelPortability.UseActiveProviderStoreTypes(modelBuilder);
#pragma warning restore 612, 618
        }
    }
}
