// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodePilot.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NodePilot.Data.Migrations
{
    [DbContext(typeof(NodePilotDbContext))]
    partial class NodePilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NodePilot.Core.Models.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<Guid?>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Username")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.HasIndex("Action", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("IpAddress", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("ResourceId", "Timestamp");

                    b.HasIndex("UserId", "Timestamp");

                    b.HasIndex("Username", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("AuditLog");
                });

            modelBuilder.Entity("NodePilot.Core.Models.AuthSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AuthenticationMethod")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int>("AuthorizationVersion")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CurrentJti")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("RefreshGeneration")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime?>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("UserId");

                    b.ToTable("AuthSessions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ClusterLeader", b =>
                {
                    b.Property<string>("Resource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastRenewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("LeaseEpoch")
                        .HasColumnType("bigint");

                    b.Property<string>("OwnerNodeId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Resource");

                    b.ToTable("ClusterLeaders");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Credential", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Domain")
                        .HasColumnType("text");

                    b.Property<byte[]>("EncryptedPassword")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Credentials");
                });

            modelBuilder.Entity("NodePilot.Core.Models.CustomActivityDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ConcurrencyToken")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DefaultTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("InputParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("Isolated")
                        .HasColumnType("boolean");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<int?>("MaxProcesses")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryLimitMb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RunsRemote")
                        .HasColumnType("boolean");

                    b.Property<string>("ScriptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuccessExitCodes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Key");

                    b.HasIndex("IsDeleted", "IsEnabled");

                    b.ToTable("CustomActivityDefinitions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.CustomActivityDefinitionVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Color")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("DefaultTimeoutSeconds")
                        .HasColumnType("integer");

                    b.Property<Guid>("DefinitionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Engine")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("InputParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("Isolated")
                        .HasColumnType("boolean");

                    b.Property<int?>("MaxProcesses")
                        .HasColumnType("integer");

                    b.Property<int?>("MemoryLimitMb")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("OutputParametersJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("RunsRemote")
                        .HasColumnType("boolean");

                    b.Property<string>("ScriptTemplate")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SuccessExitCodes")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefinitionId", "Version")
                        .IsUnique();

                    b.ToTable("CustomActivityDefinitionVersions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.DirectoryMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<string>("GroupKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Authority", "GroupKey");

                    b.HasIndex("UserId", "Authority", "GroupKey")
                        .IsUnique();

                    b.ToTable("DirectoryMemberships");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ExternalIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.HasIndex("Authority", "Subject")
                        .IsUnique();

                    b.ToTable("ExternalIdentities");
                });

            modelBuilder.Entity("NodePilot.Core.Models.GlobalVariable", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("FolderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("00000000-0000-0000-0000-000000000002"));

                    b.Property<bool>("IsSecret")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("GlobalVariables");
                });

            modelBuilder.Entity("NodePilot.Core.Models.GlobalVariableFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("ParentFolderId", "Name")
                        .IsUnique();

                    b.ToTable("GlobalVariableFolders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 0,
                            Name = "Root",
                            Path = "/"
                        });
                });

            modelBuilder.Entity("NodePilot.Core.Models.IdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.HasIndex("Key", "WorkflowId")
                        .IsUnique();

                    b.ToTable("IdempotencyKeys");
                });

            modelBuilder.Entity("NodePilot.Core.Models.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CronExpression")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("DeferralPolicy")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int?>("DurationMinutes")
                        .HasColumnType("integer");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Mode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("OneTimeEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("OneTimeStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Recurrence")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("WeeklyDaysMask")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyEndMinuteOfDay")
                        .HasColumnType("integer");

                    b.Property<int?>("WeeklyStartMinuteOfDay")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MaintenanceWindows");
                });

            modelBuilder.Entity("NodePilot.Core.Models.MaintenanceWindowTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaintenanceWindowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("MaintenanceWindowId", "TargetKind", "TargetId")
                        .IsUnique();

                    b.ToTable("MaintenanceWindowTargets");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ManagedMachine", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DefaultCredentialId")
                        .HasColumnType("uuid");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsReachable")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("LastConnectivityCheck")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<bool>("UseSsl")
                        .HasColumnType("boolean");

                    b.Property<int>("WinRmPort")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DefaultCredentialId");

                    b.ToTable("ManagedMachines");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationDeliveryAttempt", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Error")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("EventKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsTest")
                        .HasColumnType("boolean");

                    b.Property<Guid>("NotificationRouteId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Summary")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("NotificationRuleId", "NotificationRouteId", "EventKey")
                        .IsUnique();

                    b.ToTable("NotificationDeliveryAttempts");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationDispatcherState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("LastCompletedAtSeen")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("LastIdSeen")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("NotificationDispatcherStates");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ConditionExpressionJson")
                        .HasColumnType("text");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Secret")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRuleId");

                    b.ToTable("NotificationRoutes");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CooldownMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DedupKeyTemplate")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("EventTypes")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("FilterExpressionJson")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("Custom");

                    b.Property<int>("MinOccurrences")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("OccurrenceWindowMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("ScopeKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SeverityOverride")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SourceParametersJson")
                        .HasColumnType("text");

                    b.Property<int>("SustainForSeconds")
                        .HasColumnType("integer");

                    b.Property<string>("SystemPresetId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("SystemSourceId")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("IsEnabled");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("Kind", "IsEnabled");

                    b.ToTable("NotificationRules");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationRuleTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("TargetId");

                    b.HasIndex("NotificationRuleId", "TargetKind", "TargetId")
                        .IsUnique();

                    b.ToTable("NotificationRuleTargets");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationSuppressionState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<DateTime?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("WindowStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("NotificationRuleId", "DedupKey")
                        .IsUnique();

                    b.ToTable("NotificationSuppressionStates");
                });

            modelBuilder.Entity("NodePilot.Core.Models.OidcLoginTicket", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("ProtectedPayload")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("OidcLoginTickets");
                });

            modelBuilder.Entity("NodePilot.Core.Models.RevokedToken", b =>
                {
                    b.Property<string>("Jti")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Reason")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Jti");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("RevokedTokens");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ScimGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Authority")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(384)
                        .HasColumnType("character varying(384)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTombstoned")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("DisplayName");

                    b.HasIndex("Authority", "ExternalId")
                        .IsUnique();

                    b.ToTable("ScimGroups");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedFolderPermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("GrantedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("GrantedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("PrincipalAuthority")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasDefaultValue("");

                    b.Property<string>("PrincipalKey")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PrincipalType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("FolderId");

                    b.HasIndex("FolderId", "PrincipalType", "PrincipalAuthority", "PrincipalKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SharedFolderPermissions_Principal");

                    b.ToTable("SharedFolderPermissions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedWorkflowFolder", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<int>("Depth")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid?>("ParentFolderId")
                        .HasColumnType("uuid");

                    b.Property<string>("Path")
                        .IsRequired()
                        .HasMaxLength(800)
                        .HasColumnType("character varying(800)");

                    b.HasKey("Id");

                    b.HasIndex("ParentFolderId");

                    b.HasIndex("ParentFolderId", "Name")
                        .IsUnique();

                    b.ToTable("SharedWorkflowFolders");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CreatedAt = new DateTime(2020, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Depth = 0,
                            Name = "Root",
                            Path = "/"
                        });
                });

            modelBuilder.Entity("NodePilot.Core.Models.StepExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomActivityHash")
                        .HasColumnType("text");

                    b.Property<string>("CustomActivityKey")
                        .HasColumnType("text");

                    b.Property<int?>("CustomActivityVersion")
                        .HasColumnType("integer");

                    b.Property<string>("ErrorOutput")
                        .HasColumnType("text");

                    b.Property<string>("Output")
                        .HasColumnType("text");

                    b.Property<string>("OutputParametersJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PausedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StepId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StepName")
                        .HasColumnType("text");

                    b.Property<string>("StepType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TargetMachine")
                        .HasColumnType("text");

                    b.Property<string>("TraceOutput")
                        .HasColumnType("text");

                    b.Property<string>("VariablesSnapshot")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowExecutionId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowExecutionId", "StartedAt");

                    b.HasIndex("WorkflowExecutionId", "Status");

                    b.ToTable("StepExecutions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SupportEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<Guid?>("ExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ExecutionShort")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("PropertiesJson")
                        .HasMaxLength(8000)
                        .HasColumnType("character varying(8000)");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("StepId")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("StepLabel")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("UserName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkflowName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp")
                        .IsDescending();

                    b.HasIndex("EventType", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("ExecutionId", "Timestamp");

                    b.HasIndex("Level", "Timestamp")
                        .IsDescending(false, true);

                    b.HasIndex("WorkflowName", "Timestamp")
                        .IsDescending(false, true);

                    b.ToTable("SupportEvents");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SystemAlertPolicyState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EpisodeStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InstanceKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("IsMatching")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastObservedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("MatchStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NotificationRuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("LastObservedAt");

                    b.HasIndex("NotificationRuleId", "SourceId", "InstanceKey")
                        .IsUnique();

                    b.ToTable("SystemAlertPolicyStates");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SystemAlertSourceState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CursorJson")
                        .HasColumnType("text");

                    b.Property<string>("SourceId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("StateKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("SourceId", "StateKey")
                        .IsUnique();

                    b.ToTable("SystemAlertSourceStates");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SystemHealthHeartbeat", b =>
                {
                    b.Property<string>("ServiceName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("ExpectedIntervalSeconds")
                        .HasColumnType("integer");

                    b.Property<DateTime>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("ServiceName");

                    b.ToTable("SystemHealth");
                });

            modelBuilder.Entity("NodePilot.Core.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DirectorySyncStatus")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsBreakGlass")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTombstoned")
                        .HasColumnType("boolean");

                    b.Property<string>("KnownGroupSidsJson")
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastDirectorySyncAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockedUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("SecurityStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.HasIndex("Provider", "ExternalId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Workflow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ActivityCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CheckedOutAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CheckedOutByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<Guid>("FolderId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("PublishedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("TriggerTypesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CheckedOutByUserId");

                    b.HasIndex("FolderId");

                    b.ToTable("Workflows");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowExecution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CallDepth")
                        .HasColumnType("integer");

                    b.Property<string>("CancelledBy")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ErrorMessage")
                        .HasColumnType("text");

                    b.Property<string>("InputParametersJson")
                        .HasColumnType("text");

                    b.Property<string>("OwnerNodeId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid?>("ParentExecutionId")
                        .HasColumnType("uuid");

                    b.Property<string>("ReturnData")
                        .HasColumnType("text");

                    b.Property<string>("SpanId")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("StartedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("TraceId")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("TriggeredBy")
                        .HasColumnType("text");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParentExecutionId");

                    b.HasIndex("TraceId");

                    b.HasIndex("CompletedAt", "Id")
                        .HasAnnotation("SqlServer:Include", new[] { "Status" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("CompletedAt", "Id"), new[] { "Status" });

                    b.HasIndex("StartedAt", "Status");

                    b.HasIndex("Status", "StartedAt")
                        .IsDescending(false, true)
                        .HasAnnotation("SqlServer:Include", new[] { "WorkflowId", "CompletedAt", "TriggeredBy" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("Status", "StartedAt"), new[] { "WorkflowId", "CompletedAt", "TriggeredBy" });

                    b.HasIndex("WorkflowId", "StartedAt")
                        .IsDescending(false, true)
                        .HasAnnotation("SqlServer:Include", new[] { "Status", "CompletedAt" });

                    NpgsqlIndexBuilderExtensions.IncludeProperties(b.HasIndex("WorkflowId", "StartedAt"), new[] { "Status", "CompletedAt" });

                    b.ToTable("WorkflowExecutions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowStats", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<double?>("AvgDurationMsWindow")
                        .HasColumnType("double precision");

                    b.Property<int>("CancelledWindow")
                        .HasColumnType("integer");

                    b.Property<int>("FailedWindow")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("LastExecutionAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastFailureAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LastSuccessAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double?>("P50DurationMsWindow")
                        .HasColumnType("double precision");

                    b.Property<double?>("P95DurationMsWindow")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("RefreshedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SucceededWindow")
                        .HasColumnType("integer");

                    b.Property<int>("TotalExecutions")
                        .HasColumnType("integer");

                    b.Property<int>("WindowDays")
                        .HasColumnType("integer");

                    b.HasKey("WorkflowId");

                    b.ToTable("WorkflowStats");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId", "Version")
                        .IsUnique();

                    b.ToTable("WorkflowVersions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.AuthSession", b =>
                {
                    b.HasOne("NodePilot.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NodePilot.Core.Models.CustomActivityDefinitionVersion", b =>
                {
                    b.HasOne("NodePilot.Core.Models.CustomActivityDefinition", "Definition")
                        .WithMany()
                        .HasForeignKey("DefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Definition");
                });

            modelBuilder.Entity("NodePilot.Core.Models.DirectoryMembership", b =>
                {
                    b.HasOne("NodePilot.Core.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NodePilot.Core.Models.ExternalIdentity", b =>
                {
                    b.HasOne("NodePilot.Core.Models.User", "User")
                        .WithMany("ExternalIdentities")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("NodePilot.Core.Models.GlobalVariable", b =>
                {
                    b.HasOne("NodePilot.Core.Models.GlobalVariableFolder", null)
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NodePilot.Core.Models.GlobalVariableFolder", b =>
                {
                    b.HasOne("NodePilot.Core.Models.GlobalVariableFolder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NodePilot.Core.Models.MaintenanceWindowTarget", b =>
                {
                    b.HasOne("NodePilot.Core.Models.MaintenanceWindow", null)
                        .WithMany("Targets")
                        .HasForeignKey("MaintenanceWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodePilot.Core.Models.ManagedMachine", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Credential", "DefaultCredential")
                        .WithMany()
                        .HasForeignKey("DefaultCredentialId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("DefaultCredential");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationRoute", b =>
                {
                    b.HasOne("NodePilot.Core.Models.NotificationRule", "Rule")
                        .WithMany("Routes")
                        .HasForeignKey("NotificationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rule");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationRuleTarget", b =>
                {
                    b.HasOne("NodePilot.Core.Models.NotificationRule", null)
                        .WithMany("Targets")
                        .HasForeignKey("NotificationRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedFolderPermission", b =>
                {
                    b.HasOne("NodePilot.Core.Models.SharedWorkflowFolder", "Folder")
                        .WithMany("Permissions")
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedWorkflowFolder", b =>
                {
                    b.HasOne("NodePilot.Core.Models.SharedWorkflowFolder", null)
                        .WithMany()
                        .HasForeignKey("ParentFolderId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("NodePilot.Core.Models.StepExecution", b =>
                {
                    b.HasOne("NodePilot.Core.Models.WorkflowExecution", "WorkflowExecution")
                        .WithMany("Steps")
                        .HasForeignKey("WorkflowExecutionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("WorkflowExecution");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Workflow", b =>
                {
                    b.HasOne("NodePilot.Core.Models.SharedWorkflowFolder", "Folder")
                        .WithMany()
                        .HasForeignKey("FolderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Folder");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowExecution", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Workflow", "Workflow")
                        .WithMany("Executions")
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowStats", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowVersion", b =>
                {
                    b.HasOne("NodePilot.Core.Models.Workflow", "Workflow")
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Workflow");
                });

            modelBuilder.Entity("NodePilot.Core.Models.MaintenanceWindow", b =>
                {
                    b.Navigation("Targets");
                });

            modelBuilder.Entity("NodePilot.Core.Models.NotificationRule", b =>
                {
                    b.Navigation("Routes");

                    b.Navigation("Targets");
                });

            modelBuilder.Entity("NodePilot.Core.Models.SharedWorkflowFolder", b =>
                {
                    b.Navigation("Permissions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.User", b =>
                {
                    b.Navigation("ExternalIdentities");
                });

            modelBuilder.Entity("NodePilot.Core.Models.Workflow", b =>
                {
                    b.Navigation("Executions");
                });

            modelBuilder.Entity("NodePilot.Core.Models.WorkflowExecution", b =>
                {
                    b.Navigation("Steps");
                });
#pragma warning restore 612, 618
        }
    }
}
